name: Qumin
channels:
  - conda-forge
  - defaults
dependencies:
- python>=3.6
- pandas
- numpy
- scipy
- matplotlib
- networkx
- pygraphviz
- tqdm 
- seaborn
- tabulate 
- pip
- pip:
    - concepts
    - prettytable
