defaults:
  - help
  - qumin
  - _self_

# These should not be overriden
scriptname: lattice
descr: Infer Inflection classes as a lattice from alternation patterns.


patterns: null        # pre-computed patterns
pats:
  ortho: False        # whether patterns were orthographic
lattice:
  shorten: False      # Drop redundant columns altogether.
                      #  Useful for big contexts, but loses information.
                      # The lattice shape and stats will be the same.
                      # Avoid using with --html
  aoc: False          # Only attribute and object concepts

export:
  html: False         # Export to html
  ctxt: False         # Export as a context
  stat: False         # Output stats about the lattice
  pdf: True           # Export as pdf
  png: False          # Export as png